name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List all projects
      id: list
      run: |
        echo "::set-output name=projects::$(find . -name 'Cargo.toml' -exec dirname {} \;)"
    - name: Build
      run: |
        for project in ${{ steps.list.outputs.projects }}; do
          cd $project
          cargo build --verbose
          cd -
        done
    - name: Run tests
      run: |
        for project in ${{ steps.list.outputs.projects }}; do
          cd $project
          cargo test --verbose
          cd -
        done
